#纪念日开始的日子
startDay: "2016/6/24"
#当地拼音,需要在下面的墨迹天气url确认
local: "zhejiang/hangzhou"
#邮件服务商 可选值为SMTP或sendGrid
emailDelivery: "sendGrid"

#若邮件服务商为SMTP
SMTP: {
  #邮件厂商：如126
  emailService: "",
  #发送者邮箱账户SMTP授权码
  emailAuth: {
    #例如xx@126.com
    user: "",
    pass: ""
  }
}

#若邮件服务商为sendGrid
sendGrid: {
  SENDGRID_API_KEY: ''
}

emailFrom: 'ee@ine.edu'
emailTo:  "xingru@ucsb.edu"
emailSubject: '一封暖暖的小邮件'

#是否定时发送
schedule: false

#每日发送时间 int type
emailHour: 5
emialMinminute: 20